name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up Surrealdb
      run: |
          curl -sSf https://install.surrealdb.com | sh
          surreal start --log debug --user root --pass root memory &

    # TODO: set up with surrealdb
    - name: Run the default task
      run: bundle exec rake
      env:
        DATABASE_HOST: localhost
